// HelloWorld.tsx - Atlas Harness RPG smoke component
// Generated by Atlas Player as E2E harness validation
// Quest: Q-D (boss fight chain, frontend trivial sub-quest)
import React from 'react';

export function HelloWorld() {
  return (
    <div className="atlas-rojo-negro">
      <h1>Atlas Harness RPG</h1>
      <p>Rojo y Negro, como el Atlas de la Liga MX</p>
    </div>
  );
}
